gText_Birch_Welcome::
	.string "Hrmm, kept you waiting, huh?\p"
	.string "Welcome to the world of Repainted!\p"
	.string "My name is Andy.\p"
	.string "But everyone calls me the Obligatory\n"
	.string "Pokémon Professor.\n"
	.string "(Nobody calls me that.)\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Is this a pigeon?\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Dumb jokes aside...\n"
	.string "This world is completely infested by\n"
	.string "la creatura known as Pokémon.\p"
	.string "We gaymers live alongside Pokémon,\n"
	.string "sometimes as friendly playmates, and\l"
	.string "sometimes as depraved r34 searches.\p"
	.string "And sometimes, we band together\n"
	.string "and beat the shit out of each other.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "Like... why does this one have\n"
	.string "Chowder's face on it?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But enough about me...\n"
	.string "how about you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a (REDACTED)?\n"
	.string "Or are you a (DATA EXPUNGED)?$"

gText_Birch_WhatsYourName::
	.string "Gotta be one of my favorite\l"
	.string "genders. Now, what's\l"
	.string "your gamertag?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\l"
	.string "And not Chungy? You sure?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "Jeearre Town. I get it now!\l"
	.string "Hah, good luck paying rent there!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Stand proud, and leap into the\n"
	.string "world of Repainted where memes,\l"
	.string "adventure, and dinnerfarts await!\p"
	.string "Be like Eminem and come back\n"
	.string "to the lab again!\n"
	.string "See you later, bozo!\p"
	.string "$"
