gText_ObtainedTheItem::
	.string "You got a {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Your bag's full, stupid!$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Your bag's full, stupid!$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the prison wallet.$"

gText_ObtainedTheDecor::
	.string "You got a {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "You have too many {STR_VAR_2}s.\n"
	.string "I think you have a problem.$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
